name: Spanners
favicon: null
layout_spectrum: 0.42314
typography_spectrum: 0.98033
title: SPANNERS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4b5b7'
    - '#0e0e0e'
    - '#f8ffff'
    - '#558943'
    - '#c22336'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
