name: Spanners
favicon: null
layout_spectrum: 0.42314
typography_spectrum: 0.854229396674782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f9497'
    - '#a5bbbe'
    - '#362827'
    - '#634f50'
    - '#886a6a'
  brandStrength: 0.4375
  lightness: 0.39418291742913425
  saturation: 0.875
  rhythmicContrast: 0.9584353829268366
purpose: []
