typography_spectrum: 0.98033
color:
  brandColors:
    - '#b4b5b7'
    - '#0e0e0e'
    - '#f8ffff'
    - '#558943'
    - '#c22336'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.42314
analytics:
  google: null
  facebook: null
  twitter: null
name: Spanners
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Second Link !!!
    id: 539dbced-e9ae-4275-9d0b-1ec292cafa97
    type: content
favicon: null
title: SPANNERS
purpose: []
